### ISSUE TITLE
Still missing from packagist.org

### ISSUE THREAD

**Issue by kkatpcc** [Brightspace/valence-sdk-php#10]
It looks like the composer name was normalized to "brightspace/valence-sdk-php" [in 2019](https://github.com/Brightspace/valence-sdk-php/pull/8), but the entry is still missing from https://packagist.org/ despite the [related comment](https://github.com/Brightspace/valence-sdk-php/pull/8#issuecomment-454457302).

**Comment by Peter-The-Great** [comment]
I think i would like to add that....... Oh wait I ALREADY DID:
BOYA: [brightspace/valence-sdk-php](https://packagist.org/packages/brightspace/valence-sdk-php)

**Comment by kkatpcc** [comment]
https://packagist.org/packages/brightspace/valence-sdk-php was missing/hidden at the time I reported this. Seems to be there now as per the last comment. Closing this issue.

**Comment by Peter-The-Great** [comment]
Yippee
