### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by CMDann** [Brightspace/valence-sdk-php#6]
I notice that the development of the PHP sdk has been stopped for over a year. Are you still maintaing this project?

We are looking at building an integration and want to make sure the product isn't dead first.

**Comment by ViktorAtD2L** [comment]
The product isn't dead at all; the functionality in this project is actually quite stable and simple. If you want to use this project in your code, and you run into problems, we'll happily address them.

**Comment by CMDann** [comment]
Awesome, thats what I like to hear. Also thanks for the super prompt response.
