### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by ghost** [Brightspace/valence-sdk-php#9]
Hi
I have setup this SDK but on authentication getting error

This application is not authorized on this LMS instance. Ask your administrator to authorize this application.

**Comment by j3parker** [comment]
Did you get an appID and appKey? Can you paste a snippet of your code here, taking care to not post those credentials?

**Comment by ghost** [comment]
Hi j3parker, Thanks for reply,

I think the issue is with application status is showing pending. I have created application on https://keytool.valence.desire2learn.com/App/ on 12:56PM 27/12/2019. But its not activated yet.

I don't know what i am missing. can you help me out regarding this.

**Comment by j3parker** [comment]
Yep that’ll be an issue.

You’ll have to follow up through support channels, not GitHub. 

If you create the application through the LE (Admin Tools > Manage Extensibility) rather than keytool it will be automatically approved.

**Comment by j3parker** [comment]
Closing this because it isn’t an issue with the PHP SDK.
